version: '3.9'
services:
  app:
    container_name: commission_calculator_php
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/task/commision-calculator
    working_dir: /var/task/commision-calculator